// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_92Kh-Z1__d4N29MYBjsz60vpQ2dI490',
    appId: '1:972032257860:web:684f24a14e1b780c9eb111',
    messagingSenderId: '972032257860',
    projectId: 'mzikihub-iplayer',
    authDomain: 'mzikihub-iplayer.firebaseapp.com',
    storageBucket: 'mzikihub-iplayer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKIwEJ3HR5_DSpp3uMK9qTuYD3UpqwKk',
    appId: '1:972032257860:android:89cb6d37d28269019eb111',
    messagingSenderId: '972032257860',
    projectId: 'mzikihub-iplayer',
    storageBucket: 'mzikihub-iplayer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVELe2JbUAKkRXqXz0-NXOHqYF3CBS8E',
    appId: '1:972032257860:ios:806ced259bf54b869eb111',
    messagingSenderId: '972032257860',
    projectId: 'mzikihub-iplayer',
    storageBucket: 'mzikihub-iplayer.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );
}
